#!/usr/bin/perl

use strict;
use warnings;

my $tool = "../nbtool";

die "run make in parent directory!\n" unless -x $tool;

my @tests;
for (glob "*.schematic *.nbt") {
    push @tests, $_ if -e "$_.ans";
}

my $num_failed=0;

for my $test (@tests) {
    `$tool -v $test 2> $test.out`;
    `diff $test.out $test.ans`;
    print "$test failed\n" if $?;
    $num_failed++ if $?;
}

print scalar @tests . " tests conducted, $num_failed failed.\n";
exit $num_failed;
