#!/bin/bash

# exit immediately if a command fails
set -e

ECC=../ezip

if [ ! -x ${ECC} ]; then echo "run \"make\" first, then try again"; exit -1; fi

for f in abcd hello ones pairs rand many-ones
do
  echo testing $f
  echo encoding...
  ${ECC} $1 -i $f -o $f.enc
  echo decoding...
  ${ECC} $1 -d -i $f.enc -o $f.dec
  #ls -lt $f $f.dec
  echo -n diffing...
  diff -q $f $f.dec
  if [ $? -eq 0 ]; then echo ok; fi
  rm -f $f.enc $f.dec
  echo ------------
done
